#! /usr/bin/env bash
# caseans
echo -n "Do you wish to proceed [y..n] :"
read ANS
case $ANS in
y|Y|yes|Yes)
echo "Yes is selected"
;;
n|N|no)
echo "No is selected"
exit 0 # Нет ошибки, поэтому 0
;;
*)
echo "`basename $0` Unknown response" >&2
;;
esac
