#! /usr/bin/env bash
# func2
char_name() 
# проверка на предмет того, действительно ли
# $1 содержит только символы a-z,A-Z
{
_LETTERS_ONLY=$1
_LETTERS_ONLY=`echo $1 | awk '{if( $0~/[^a-z A-Z]/) print "1"}'`
if [ "$_LETTERS_ONLY" != "" ]; then
	return 1
else
	return 0
fi
}
name_error()
# отображение сообщения об ошибке
{
echo "$@ contains errors, it must contain only letters"
}
while :
do
echo -n "What is you first name : "
read F_NAME
if char_name $F_NAME; then
	break
else
	name_error $F_NAME
fi
done
while :
do
echo -n "What is you surname : "
read S_NAME
if char_name $S_NAME; then
	break
else
	name_error $S_NAME
fi
done
