#! /usr/bin/env bash
# ifmkdir
DIRECTORY=$1
if [ $# -lt 1 ]; then
	echo "Usage: `basename $0` directory to create " >&2
	exit 1
fi

if [ -d $DIRECTORY ]
then :
else
	echo "The directory does exist"
	echo -n "Create it now? [y..n] :"
	read ANS
	if [ "$ANS" = "y" ] || [ "$ANS" = "Y" ] 
	then	
		echo "Creating now"
		mkdir $DIRECTORY > /dev/null 2>&1
		if [ $? != 0 ]; then
			echo "Errors creating the directory $DIRECTORY" >&2
			exit 1
		fi
	else :
	fi
fi
