#! /usr/bin/env bash
# menu

# Установка даты, имени пользователя и хоста
MYDATE=`date +%d/%m/%Y`
THIS_HOST=`hostname -s`
USER=`whoami`
# Бесконечный цикл
while :
do
# Очистка экрана с помощью команды tput
# Здесь начинается конструкция "документ здесь"
cat << MAYDAY
---------------------------------------------------------------
User: $USER		Host: $THIS_HOST	  Date: $MYDATE
---------------------------------------------------------------
		1 : List files in current directory
		2 : Use the vi editor
		3 : See who is on the system
		H : Help screen
		Q : Exit menu
MAYDAY
# Завершение конструкции "документ здесь"
echo -e -n "\tYour Choice [1,2,3,H,Q] >"
read CHOICE
case $CHOICE in
	1) ls ;;
	2) vi ;;
	3) who ;;
	H|h)
	# Использование конструкции "документ здесь" для экрана помощи
	cat << MAYDAY
	This is the help screen, nothing here yet to help you!
MAYDAY
	;;
	Q|q) exit 0 ;;
	*)echo -e "\t\007Unknown user response" ;;
esac
echo -e -n "\tHit the return key to continue"
read DUMMY
done
