#! /usr/bin/env bash
# my_test

#. functions.main
characters()
{
# characters
# Проверка строки на наличие исключительно символьных данных
_LETTERS_ONLY=$1
_LETTERS_ONLY=`echo $1 | awk '{if($0~/[^a-zA-Z]/) print "1"}'`
if [ "$_LETTERS_ONLY" != "" ]; then
	return 1
else
	return 0
fi
}

if characters q1w; then
	echo "Символы"
else
	echo "И числа"
fi
